[workspace]
members = [
    "asset-compiler",
    "build-hash",
    "metal-app",
    "metal-build",
    "metal-shaders",
    "metal-types",
    "png-add-alpha",
    "proj-*/",
    "x-rt/"
]

[profile.dev.package."*"]
opt-level = 3