[workspace]
members = [
    "asset-compiler",
    "build-hash",
    "metal-app",
    "metal-build",
    "metal-shaders",
    "metal-types",
    "png-add-alpha",
    "proj-1-*/",
    "proj-2-*/",
    "proj-3-*/",
    "proj-4-*/",
    "yolo"
]

[profile.dev.package."*"]
opt-level = 3