[package]
name = "asset-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

metal = { git = "https://github.com/peterwmwong/metal-rs.git", rev = "380db143b9526df1f1c81a4cabcbfd051beefaf7" }
png = "0.17.5"
