#![allow(non_upper_case_globals, non_snake_case)]
/**************************************************************************************************
 GENERATED FILE. DO NOT MODIFY.

 This file is generated by the `metal_build` crate, check you're `build.rs` for
 `metal_build::build()`.
 Structs and Enums are generated based on `src/shader_bindings.h` and `src/shaders.metal`.
***************************************************************************************************/
#[allow(unused_imports)]
use metal_app::{metal::*, metal_types::*, pipeline::*};

/****************
 Shader functions
*****************/

#[allow(non_camel_case_types)]
pub struct gbuf_vertex_binds<'c> {
    pub geometry: Bind<'c, GeometryNoTxCoords>,
    pub model: Bind<'c, ModelSpace>,
}
impl Binds for gbuf_vertex_binds<'_> {
    const SKIP: Self = Self {
        geometry: Bind::Skip,
        model: Bind::Skip,
    };

    #[inline(always)]
    fn bind<F: PipelineFunctionType>(self, encoder: &F::CommandEncoder) {
        self.geometry.bind::<F>(encoder, 0);
        self.model.bind::<F>(encoder, 1);
    }
}

#[allow(non_camel_case_types)]
pub struct gbuf_vertex;
impl metal_app::pipeline::function::Function for gbuf_vertex {
    const FUNCTION_NAME: &'static str = "gbuf_vertex";
    type Binds<'c> = gbuf_vertex_binds<'c>;
}
impl PipelineFunction<VertexFunctionType> for gbuf_vertex {}

#[allow(non_camel_case_types)]
pub struct gbuf_fragment;
impl metal_app::pipeline::function::Function for gbuf_fragment {
    const FUNCTION_NAME: &'static str = "gbuf_fragment";
    type Binds<'c> = NoBinds;
}
impl PipelineFunction<FragmentFunctionType> for gbuf_fragment {}

#[allow(non_camel_case_types)]
pub struct lighting_vertex;
impl metal_app::pipeline::function::Function for lighting_vertex {
    const FUNCTION_NAME: &'static str = "lighting_vertex";
    type Binds<'c> = NoBinds;
}
impl PipelineFunction<VertexFunctionType> for lighting_vertex {}

#[allow(non_camel_case_types)]
pub struct lighting_fragment_binds<'c> {
    pub camera: Bind<'c, ProjectedSpace>,
    pub light_pos: Bind<'c, float4>,
}
impl Binds for lighting_fragment_binds<'_> {
    const SKIP: Self = Self {
        camera: Bind::Skip,
        light_pos: Bind::Skip,
    };

    #[inline(always)]
    fn bind<F: PipelineFunctionType>(self, encoder: &F::CommandEncoder) {
        self.camera.bind::<F>(encoder, 0);
        self.light_pos.bind::<F>(encoder, 1);
    }
}

#[allow(non_camel_case_types)]
pub struct lighting_fragment {
    pub HasAmbient: bool,
    pub HasDiffuse: bool,
    pub OnlyNormals: bool,
    pub HasSpecular: bool,
}
impl metal_app::pipeline::function::Function for lighting_fragment {
    const FUNCTION_NAME: &'static str = "lighting_fragment";
    type Binds<'c> = lighting_fragment_binds<'c>;
    #[inline]
    fn get_function_constants(&self) -> Option<FunctionConstantValues> {
        let fcv = FunctionConstantValues::new();
        fcv.set_constant_value_at_index((&self.HasAmbient as *const _) as _, bool::MTL_DATA_TYPE, 0);
        fcv.set_constant_value_at_index((&self.HasDiffuse as *const _) as _, bool::MTL_DATA_TYPE, 1);
        fcv.set_constant_value_at_index((&self.OnlyNormals as *const _) as _, bool::MTL_DATA_TYPE, 2);
        fcv.set_constant_value_at_index((&self.HasSpecular as *const _) as _, bool::MTL_DATA_TYPE, 3);
        Some(fcv)
    }
}
impl PipelineFunction<FragmentFunctionType> for lighting_fragment {}

#[allow(non_camel_case_types)]
pub struct light_vertex_binds<'c> {
    pub camera: Bind<'c, ProjectedSpace>,
    pub light_pos: Bind<'c, float4>,
}
impl Binds for light_vertex_binds<'_> {
    const SKIP: Self = Self {
        camera: Bind::Skip,
        light_pos: Bind::Skip,
    };

    #[inline(always)]
    fn bind<F: PipelineFunctionType>(self, encoder: &F::CommandEncoder) {
        self.camera.bind::<F>(encoder, 0);
        self.light_pos.bind::<F>(encoder, 1);
    }
}

#[allow(non_camel_case_types)]
pub struct light_vertex;
impl metal_app::pipeline::function::Function for light_vertex {
    const FUNCTION_NAME: &'static str = "light_vertex";
    type Binds<'c> = light_vertex_binds<'c>;
}
impl PipelineFunction<VertexFunctionType> for light_vertex {}

#[allow(non_camel_case_types)]
pub struct light_fragment;
impl metal_app::pipeline::function::Function for light_fragment {
    const FUNCTION_NAME: &'static str = "light_fragment";
    type Binds<'c> = NoBinds;
}
impl PipelineFunction<FragmentFunctionType> for light_fragment {}
