#![allow(deref_nullptr, non_upper_case_globals, non_snake_case)]
/**************************************************************************************************
 GENERATED FILE. DO NOT MODIFY.

 This file is generated by the `metal_build` crate, check you're `build.rs` for
 `metal_build::build()`.
 Structs and Enums are generated based on `shader_src/shader_bindings.h`.
***************************************************************************************************/
#[allow(unused_imports)]
use metal_app::metal_types::*;
/* automatically generated by rust-bindgen 0.60.1 */

pub const INITIAL_CAMERA_DISTANCE: f32 = 50.0;
#[repr(i32)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum VertexBufferIndex {
    MaxPositionValue = 0,
    Positions = 1,
    ScreenSize = 2,
    CameraRotation = 3,
    CameraDistance = 4,
    UsePerspective = 5,
    LENGTH = 6,
}
