#![allow(deref_nullptr, non_upper_case_globals, non_snake_case)]
/**************************************************************************************************
 GENERATED FILE. DO NOT MODIFY.

 This file is generated by the `metal_build` crate, check you're `build.rs` for
 `metal_build::build()`.
 Structs and Enums are generated based on `shader_src/common.h`.
***************************************************************************************************/
#[allow(unused_imports)]
use metal_build::metal_types::*;
/* automatically generated by rust-bindgen 0.59.2 */

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VertexBufferIndex {
    Indices = 0,
    Positions = 1,
    Normals = 2,
    MatrixModelToProjection = 3,
    MatrixNormalToWorld = 4,
    LENGTH = 5,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum FragMode {
    Normals = 0,
    Ambient = 1,
    AmbientDiffuse = 2,
    Specular = 3,
    AmbientDiffuseSpecular = 4,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum FragBufferIndex {
    FragMode = 0,
    MatrixProjectionToWorld = 1,
    ScreenSize = 2,
    LightPosition = 3,
    CameraPosition = 4,
    LENGTH = 5,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LightVertexBufferIndex {
    MatrixWorldToProjection = 0,
    LightPosition = 1,
    LENGTH = 2,
}
