/**************************************************************************************************
GENERATED FILE. DO NOT MODIFY.

This file is generated by the `build.rs`.
***************************************************************************************************/
pub const TYPES: [&'static str; 23] = [
	"DebugPath",
	"Geometry",
	"GeometryNoTxCoords",
	"Material",
	"ModelSpace",
	"ProjectedSpace",
	"TriNormals",
	"float2",
	"float3x3",
	"float4",
	"float4x3",
	"float4x4",
	"half2",
	"half3",
	"half3x3",
	"half4",
	"packed_float2",
	"packed_float3",
	"packed_float4",
	"packed_half2",
	"packed_half3",
	"packed_half4",
	"ushort2",
];
