[package]
name = "proj-4-textures"
version = "0.1.0"
edition = "2021"

[build-dependencies]
metal-build = { path = "../metal-build" }

[dependencies]
metal-app = { path = "../metal-app" }
tobj = "3.2.2"
png = "0.17.5"