[package]
name = "proj-4-textures"
version = "0.1.0"
edition = "2021"

[build-dependencies]
metal-build = { path = "../metal-build" }

[dependencies]
bitflags = "1.3.2"
metal-app = { path = "../metal-app" }
png = "0.17.5"
tobj = "3.2.2"