[package]
name = "proj-1-hello-world"
version = "0.1.0"
edition = "2021"

[build-dependencies]
metal-build = { path = "../metal-build" }

[dependencies]
metal-app = { path = "../metal-app" }
half = "1.8.2"