[package]
name = "proj-6-environment-mapping"
version = "0.1.0"
edition = "2021"

[build-dependencies]
metal-build = { path = "../metal-build" }

[dependencies]
metal-app = { path = "../metal-app" }
tobj = { version = "3.2.2" }
