[package]
name = "proj-5-render-buffers"
version = "0.1.0"
edition = "2021"

[build-dependencies]
metal-build = { path = "../metal-build" }

[dependencies]
metal-app = { path = "../metal-app" }
metal-build = { path = "../metal-build" }
proj-4-textures = { path = "../proj-4-textures" }
