[package]
name = "metal-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.59.2"

[dependencies]
bindgen = "0.59.2"
metal-app = { path = "../metal-app" }