#!/bin/sh

set -e
CRATE_NAME=$1
BEFORE_POSTFIX=$2
AFTER_POSTFIX=$3
CRATE_NAME_NORMALIZED=$(echo "$CRATE_NAME" | tr "-" "_")
BEFORE_OUTPUT_PATH="/tmp/$CRATE_NAME-$BEFORE_POSTFIX.js"
AFTER_OUTPUT_PATH="/tmp/$CRATE_NAME-$AFTER_POSTFIX.js"

touch $BEFORE_OUTPUT_PATH
touch $AFTER_OUTPUT_PATH
/usr/local/bin/code-insiders -r --diff $BEFORE_OUTPUT_PATH $AFTER_OUTPUT_PATH