#![allow(deref_nullptr, non_upper_case_globals, non_snake_case)]
/**************************************************************************************************
 GENERATED FILE. DO NOT MODIFY.

 This file is generated by the `metal_build` crate, check you're `build.rs` for
 `metal_build::build()`.
 Structs and Enums are generated based on `shader_src/common.h`.
***************************************************************************************************/
#[allow(unused_imports)]
use metal_build::metal_types::*;
/* automatically generated by rust-bindgen 0.60.1 */

#[repr(u8)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum TextureFilterMode {
    Nearest = 0,
    Linear = 1,
    Mipmap = 2,
    Anistropic = 3,
}
#[repr(u8)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum VertexBufferIndex {
    MatrixModelToProjection = 0,
    LENGTH = 1,
}
#[repr(u8)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum FragBufferIndex {
    Texture = 0,
    TextureFilterMode = 1,
    LENGTH = 2,
}
